# Utiliser une image Node.js 20
image: node:20

# Définir les étapes du pipeline
stages:
  - deploy

# Mise en cache des node_modules pour accélérer les builds futurs
cache:
  paths:
    - node_modules/

# Le job qui construit et déploie le site sur GitLab Pages
pages:
  stage: deploy
  script:
    # Installer les dépendances
    - npm install
    # Construire l'application. Vite va générer le site dans le dossier "dist"
    - npm run build
    # GitLab Pages requiert que les fichiers soient dans un dossier nommé "public"
    # Nous renommons donc le dossier "dist" en "public"
    - mv dist public
    # Astuce pour les Single Page Applications (SPA) comme React :
    # Copier index.html en 404.html permet de gérer la navigation côté client.
    # Si l'utilisateur recharge une page (ex: /lecons), GitLab sert la page 404,
    # qui est en fait notre index.html, et le routeur React prend le relais.
    - cp public/index.html public/404.html
  artifacts:
    paths:
      # Le dossier qui contient le site à déployer
      - public
  rules:
    # Ce job ne s'exécute que lorsque des changements sont poussés sur la branche "master"
    - if: '$CI_COMMIT_BRANCH == "master"'
